# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7940d7de7187fa850d30236761712e232781c8241c9d86db4ef90f7846c54bba328ddc504b043f6eae20f1edd229da6cf5ea26c5516e82d20a0a3fc5034e274

test:
  secret_key_base: c65f2b056b25e81d6d1453cbcea842f07bdc25f39c1cd31b8bc0638fd0bcc2cea5ba7918b75bd7526dedbefa4f856da86d0a54875638671044e54ef762037972

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
